LOAD DATA LOCAL INFILE 'Bids.data' INTO TABLE BidModel
FIELDS TERMINATED BY '<>';

LOAD DATA LOCAL INFILE 'Offers.data' INTO TABLE OfferModel
FIELDS TERMINATED BY '<>';

LOAD DATA LOCAL INFILE 'Users.data' INTO TABLE UserModel
FIELDS TERMINATED BY '<>';

LOAD DATA LOCAL INFILE 'Investments.data' INTO TABLE InvestmentModel
FIELDS TERMINATED BY '<>';

LOAD DATA LOCAL INFILE 'Products.data' INTO TABLE ProductModel
FIELDS TERMINATED BY '<>';

